-- =============================================================================
--  AI Revenue Recovery System — PostgreSQL Schema (Neon DB Optimized)
--  Author  : Lead Data Engineer (AI Fintech Architecture)
--  Version : 1.0.0
--  Target  : PostgreSQL 15+ / Neon DB (serverless Postgres)
-- -----------------------------------------------------------------------------
--  Design Notes:
--    • UUID primary keys generated by gen_random_uuid() (pg_crypto built-in)
--    • TIMESTAMPTZ for all datetimes (timezone-aware, critical for global ops)
--    • JSONB for agent_reasoning_trace (indexed, queryable via GIN)
--    • Partial indexes to optimise frequent query patterns
--    • ENUM types for finite categorical domains (smaller storage + validation)
--    • All FK references use ON DELETE CASCADE for clean event lifecycle mgmt
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";   -- for fuzzy text search on reasons


-- ---------------------------------------------------------------------------
-- 1. ENUM TYPES  (single source of truth for categorical columns)
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    -- Payment method
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method_enum') THEN
        CREATE TYPE payment_method_enum AS ENUM (
            'UPI',
            'Credit Card',
            'Debit Card',
            'Net Banking',          -- forward-compat placeholders
            'Wallet',
            'BNPL'
        );
    END IF;

    -- Failure reason (raw, as received from payment gateway)
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'failure_reason_enum') THEN
        CREATE TYPE failure_reason_enum AS ENUM (
            'insufficient_funds',
            'gateway_timeout',
            'incorrect_pin',
            'expired_card',
            'risk_flag',
            'card_not_supported',   -- forward-compat
            'do_not_honor',
            'unknown'
        );
    END IF;

    -- AI-recommended recovery action
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recovery_action_enum') THEN
        CREATE TYPE recovery_action_enum AS ENUM (
            'retry_now',
            'retry_later',
            'switch_method',
            'give_up',
            'escalate_to_agent'     -- forward-compat
        );
    END IF;

    -- Outcome of a recovery attempt
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recovery_outcome_enum') THEN
        CREATE TYPE recovery_outcome_enum AS ENUM (
            'pending',
            'success',
            'failed',
            'expired',
            'skipped'
        );
    END IF;

END $$;


-- ---------------------------------------------------------------------------
-- 2. TABLE: failed_payments
--    Stores the initial failed payment event as ingested from the upstream
--    gateway/webhook. One row per distinct payment failure event.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS failed_payments (
    -- ── Identity ──────────────────────────────────────────────────────────────
    id                          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id              UUID            NOT NULL UNIQUE,   -- upstream TX ID
    customer_id                 UUID            NOT NULL,

    -- ── Payment Details ───────────────────────────────────────────────────────
    amount                      NUMERIC(14, 2)  NOT NULL CHECK (amount > 0),
    currency                    CHAR(3)         NOT NULL DEFAULT 'INR',
    payment_method              payment_method_enum NOT NULL,
    failure_reason_raw          failure_reason_enum NOT NULL,

    -- ── Customer Context (snapshot at time of failure) ────────────────────────
    customer_ltv                NUMERIC(14, 2)  NOT NULL DEFAULT 0.00 CHECK (customer_ltv >= 0),
    recent_retries              SMALLINT        NOT NULL DEFAULT 0    CHECK (recent_retries BETWEEN 0 AND 10),
    time_since_last_attempt_mins INT            NOT NULL DEFAULT 0    CHECK (time_since_last_attempt_mins >= 0),

    -- ── Gateway / Source Metadata ─────────────────────────────────────────────
    gateway_name                VARCHAR(64),                -- e.g. 'razorpay', 'stripe'
    gateway_error_code          VARCHAR(64),                -- raw gateway error code
    gateway_raw_payload         JSONB,                      -- full webhook body (optional)
    merchant_id                 UUID,                       -- multi-tenant support

    -- ── Lifecycle ─────────────────────────────────────────────────────────────
    failed_at                   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- ── Soft-delete / archival ────────────────────────────────────────────────
    is_archived                 BOOLEAN         NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE  failed_payments                           IS 'Immutable event log of failed payment attempts ingested from payment gateways.';
COMMENT ON COLUMN failed_payments.transaction_id            IS 'Externally generated UUID from the upstream payment system — must be unique.';
COMMENT ON COLUMN failed_payments.customer_ltv              IS 'Customer lifetime value snapshot at the time of failure, in base currency units.';
COMMENT ON COLUMN failed_payments.gateway_raw_payload       IS 'Full raw JSON payload from the payment gateway webhook for audit/replay.';


-- ---------------------------------------------------------------------------
-- 3. TABLE: recovery_decisions
--    Stores the AI agent's decision for each failed payment along with its
--    full reasoning trace. One row per agent invocation.
--    Multiple decisions per transaction are allowed (retry cycles).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS recovery_decisions (
    -- ── Identity ──────────────────────────────────────────────────────────────
    id                          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    failed_payment_id           UUID            NOT NULL
                                    REFERENCES failed_payments(id) ON DELETE CASCADE,
    transaction_id              UUID            NOT NULL,   -- denormalized for fast joins

    -- ── Agent Decision ────────────────────────────────────────────────────────
    decision                    recovery_action_enum NOT NULL,
    confidence_score            NUMERIC(5, 4)   NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
    decision_version            SMALLINT        NOT NULL DEFAULT 1, -- agent model version

    -- ── LLM Reasoning Trace (vital for React dashboard & explainability) ───────
    -- Stores the full chain-of-thought, feature importances, and rule triggers
    -- as emitted by the Python agent. Indexed with GIN for sub-field queries.
    agent_reasoning_trace       JSONB           NOT NULL,

    -- ── Recommended Action Details ────────────────────────────────────────────
    recommended_retry_delay_mins INT,                       -- if decision = retry_later
    recommended_channel         VARCHAR(64),               -- if decision = switch_method
    customer_communication_hint TEXT,                       -- short message to send user

    -- ── Execution Outcome (filled by the execution engine post-action) ─────────
    outcome                     recovery_outcome_enum NOT NULL DEFAULT 'pending',
    outcome_transaction_id      UUID,                       -- new TX if retry succeeded
    outcome_recorded_at         TIMESTAMPTZ,

    -- ── Processing Metadata ────────────────────────────────────────────────────
    agent_model_id              VARCHAR(128),               -- e.g. 'gpt-4o-2024-08-06'
    agent_latency_ms            INT,                        -- end-to-end agent latency
    prompt_tokens               INT,
    completion_tokens           INT,

    -- ── Lifecycle ─────────────────────────────────────────────────────────────
    decided_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  recovery_decisions                            IS 'AI agent decisions and full reasoning traces for each failed payment recovery attempt.';
COMMENT ON COLUMN recovery_decisions.agent_reasoning_trace      IS 'JSONB blob containing the LLM chain-of-thought, triggered rules, feature vector, and confidence breakdown. Exposed directly to the React dashboard.';
COMMENT ON COLUMN recovery_decisions.confidence_score           IS 'Agent confidence [0.0, 1.0] for the chosen recovery_action. Used to threshold human-in-the-loop escalations.';
COMMENT ON COLUMN recovery_decisions.decision_version           IS 'Version of the agent decision model — enables A/B testing and rollback audits.';


-- ---------------------------------------------------------------------------
-- 4. INDEXES — failed_payments
-- ---------------------------------------------------------------------------

-- Primary lookup: transaction_id (UUID unique — already has unique constraint)
-- Secondary fetch by customer
CREATE INDEX IF NOT EXISTS idx_fp_customer_id
    ON failed_payments (customer_id);

-- Time-series queries / dashboard analytics
CREATE INDEX IF NOT EXISTS idx_fp_failed_at
    ON failed_payments (failed_at DESC);

-- Composite: payment method + failure reason (ML feature analysis)
CREATE INDEX IF NOT EXISTS idx_fp_method_reason
    ON failed_payments (payment_method, failure_reason_raw);

-- Partial: only non-archived, recent failures (hot path for recovery engine)
CREATE INDEX IF NOT EXISTS idx_fp_active_recent
    ON failed_payments (failed_at DESC)
    WHERE is_archived = FALSE;

-- Merchant-scoped queries (multi-tenant SaaS future-proofing)
CREATE INDEX IF NOT EXISTS idx_fp_merchant_id
    ON failed_payments (merchant_id)
    WHERE merchant_id IS NOT NULL;

-- JSONB GIN index for ad-hoc gateway_raw_payload queries
CREATE INDEX IF NOT EXISTS idx_fp_gateway_payload_gin
    ON failed_payments USING GIN (gateway_raw_payload jsonb_path_ops)
    WHERE gateway_raw_payload IS NOT NULL;


-- ---------------------------------------------------------------------------
-- 5. INDEXES — recovery_decisions
-- ---------------------------------------------------------------------------

-- Primary FK join
CREATE INDEX IF NOT EXISTS idx_rd_failed_payment_id
    ON recovery_decisions (failed_payment_id);

-- Denormalized TX lookup (avoids join in hot paths)
CREATE INDEX IF NOT EXISTS idx_rd_transaction_id
    ON recovery_decisions (transaction_id);

-- Dashboard: time-ordered decisions
CREATE INDEX IF NOT EXISTS idx_rd_decided_at
    ON recovery_decisions (decided_at DESC);

-- Outcome analysis (success rate queries)
CREATE INDEX IF NOT EXISTS idx_rd_outcome
    ON recovery_decisions (outcome);

-- GIN index on agent_reasoning_trace — enables queries like:
--   WHERE agent_reasoning_trace @> '{"triggered_rules": ["insufficient_funds_high_ltv"]}'
CREATE INDEX IF NOT EXISTS idx_rd_reasoning_trace_gin
    ON recovery_decisions USING GIN (agent_reasoning_trace jsonb_path_ops);

-- High-confidence decisions (threshold dashboards)
CREATE INDEX IF NOT EXISTS idx_rd_confidence_high
    ON recovery_decisions (confidence_score DESC)
    WHERE confidence_score >= 0.80;

-- Pending decisions (recovery execution queue)
CREATE INDEX IF NOT EXISTS idx_rd_pending
    ON recovery_decisions (decided_at ASC)
    WHERE outcome = 'pending';


-- ---------------------------------------------------------------------------
-- 6. TRIGGER: auto-update updated_at on row modification
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_fp_updated_at
    BEFORE UPDATE ON failed_payments
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE OR REPLACE TRIGGER trg_rd_updated_at
    BEFORE UPDATE ON recovery_decisions
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();


-- ---------------------------------------------------------------------------
-- 7. VIEWS — convenience views for the React dashboard API layer
-- ---------------------------------------------------------------------------

-- Latest decision per transaction (avoids subquery in every dashboard query)
CREATE OR REPLACE VIEW v_latest_recovery_decision AS
SELECT DISTINCT ON (rd.transaction_id)
    rd.*,
    fp.amount,
    fp.currency,
    fp.payment_method,
    fp.failure_reason_raw,
    fp.customer_id,
    fp.customer_ltv,
    fp.failed_at
FROM recovery_decisions rd
JOIN failed_payments fp ON fp.id = rd.failed_payment_id
ORDER BY rd.transaction_id, rd.decided_at DESC;

COMMENT ON VIEW v_latest_recovery_decision IS 'Most recent AI recovery decision per transaction, joined with payment context.';

-- Daily recovery success rate (analytics / reporting)
CREATE OR REPLACE VIEW v_daily_recovery_stats AS
SELECT
    DATE_TRUNC('day', decided_at AT TIME ZONE 'Asia/Kolkata') AS day_ist,
    decision,
    outcome,
    COUNT(*)                                                   AS total,
    ROUND(AVG(confidence_score)::NUMERIC, 4)                  AS avg_confidence,
    ROUND(AVG(agent_latency_ms)::NUMERIC, 0)                  AS avg_latency_ms
FROM recovery_decisions
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 3;

COMMENT ON VIEW v_daily_recovery_stats IS 'Daily aggregate stats for recovery decisions — used by the analytics dashboard.';


-- ---------------------------------------------------------------------------
-- 8. ROW-LEVEL SECURITY (Neon / multi-tenant scaffolding)
-- ---------------------------------------------------------------------------
-- Enable RLS on both tables. Add policies when auth layer is integrated.

ALTER TABLE failed_payments     ENABLE ROW LEVEL SECURITY;
ALTER TABLE recovery_decisions  ENABLE ROW LEVEL SECURITY;

-- Superuser / service-role bypass (Neon service role has BYPASSRLS privilege)
-- Add tenant-scoped policies here when merchant_id JWT claim is available:
-- CREATE POLICY tenant_isolation ON failed_payments
--     USING (merchant_id = current_setting('app.current_merchant_id')::UUID);


-- ---------------------------------------------------------------------------
-- 9. SANITY CHECK QUERIES (run manually after migration)
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*) FROM failed_payments;
-- SELECT COUNT(*) FROM recovery_decisions;
-- SELECT * FROM v_daily_recovery_stats LIMIT 10;
-- SELECT agent_reasoning_trace->'triggered_rules'
--   FROM recovery_decisions WHERE id = '<some-uuid>';
