---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference
  namespace: airevrecovery
  labels:
    app: ml-inference
    app.kubernetes.io/component: ml-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
        - name: ml-inference
          image: ghcr.io/nitheeshp19/ai-revenue-recovery/ml-inference:latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: ml-inference-svc
  namespace: airevrecovery
spec:
  selector:
    app: ml-inference
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: airevrecovery
  labels:
    app: agent
    app.kubernetes.io/component: groq-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: ghcr.io/nitheeshp19/ai-revenue-recovery/agent:latest
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: agent-svc
  namespace: airevrecovery
spec:
  selector:
    app: agent
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
